### ISSUE TITLE
inline comments

### ISSUE THREAD

**Issue by peterpratt** [UoE-SSP/javascript-style-guide#4]
having worked with the inline comments with a new line.  Not sure this is necessary and there seems to be a preference for "descriptive" inline comments at the end of the line

**Comment by gregtyler** [comment]
So we remove the whole "single line comment" bit? I'm okay with that.

Should we take out the FIXME stuff as well? IIRC we came to agree that the wording of that isn't really appropriate, but that TODO is fine as long as we clarify that nothing "todo" should ever be shipped.

**Comment by peterpratt** [comment]
Have made changes to the inline comments, should we simple leave in the last block 
Use //TODO  to annotate solutions to problems (but should not be shipped to production)

**Comment by gregtyler** [comment]
:+1:

That seems fine to me.
